### ISSUE TITLE
Consider MIT license

### ISSUE THREAD

**Issue by beriberikix** [facebook-atom/atom-ide-debugger-native-gdb#1]
Please consider relicensing to MIT and removing the patent clause, like [React+friends](https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/) and [GraphQL](https://code.facebook.com/posts/121714468491809/relicensing-the-graphql-specification/). This would enable more companies and language communities to contribute to bringing IDE-like features to Atom.

See related issue on [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui/issues/91) as well.

**Comment by mostafaeweda** [comment]
following the same https://github.com/facebook-atom/atom-ide-ui/issues/91
