### ISSUE TITLE
error starting debugger

### ISSUE THREAD

**Issue by dpriedel** [facebook-atom/atom-ide-debugger-native-gdb#2]
Hi

I just installed this package today along with the latest version of the atom-ide package (with new debugging support).

Upon attempting to start a debug session, I get the following message:

(node:18896) UnhandledPromiseRejectionWarning: Error: Cannot find module '/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v59-linux-x64/pty.node'

I have verified there is no such file in package directory inside my .atom directory.  There is a 'v51' directory though.

Thanks

Dave Riedel

**Comment by pelmers** [comment]
This is probably because of the mismatch between the node version in Atom and the node version you have on your path. What is the output of `node -v`?

Prebuilt `pty` module is only built for node v7. I suggest downgrading if possible

Otherwise you may be able to manually build by checkout https://github.com/facebook-atom/nuclide-prebuilt-libs/tree/master/pty, `npm run build`, then copy the artifact to the correct location in the error message.

**Comment by dpriedel** [comment]
I installed node 7.1.0 and the debugger now runs.


Thanks


Dave Riedel

**Comment by dpriedel** [comment]
I've installed the update.  

I am running atom 1.26.0

I am running node 7.1.0

Here's the output I get now.
    at tryModuleLoad (module.js:466:12)
Native_gdb Debugger
4/23/2018, 2:46:13 PM
(node:8107) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module '/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v57-linux-x64/pty.node'
Native_gdb Debugger
4:22:50 PM
(node:8107) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Native_gdb Debugger
4:22:50 PM
(node:8538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module '/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v57-linux-x64/pty.node'
Native_gdb Debugger
4:27:04 PM
(node:8538) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Native_gdb Debugger
4:27:04 PM
(node:10357) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module '/home/dpriedel/.atom/packages/atom-ide-debugger-native-gdb/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v57-linux-x64/pty.node'
Native_gdb Debugger
5:00:22 PM
(node:10357) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Native_gdb Debugger
5:00:22 PM
New Messages
DEBUGGER
 
￼
Tip: Shift + Enter to insert a newline
Project
Debugger
Git


The debug target is currently running.
Call Stack
Address
File Location
callstack unavailable
Breakpoints
Uncaught exceptions
Thrown exceptions

Unit_Test.cpp:336

Unit_Test.cpp:505

Thanks

Dave Riedel
