### ISSUE TITLE
C++ STL containers

### ISSUE THREAD

**Issue by dpriedel** [facebook-atom/atom-ide-debugger-native-gdb#3]
Is it possible to display the contents of standard library containers such as vector or map?

If so, how.

When I have a variable of such a type, in the scopes tab it says 'unavailable'.

Thanks

**Comment by ebluestein** [comment]
Looks like for gdb you need to explicitly enable STL pretty printing, try issuing this command from the debugger console:

` -exec set print pretty

(Note the leading backtick, which causes Nuclide to send the command directly to GDB).

You may find a better experience using LLDB instead though.
