### ISSUE TITLE
Update the readme

### ISSUE THREAD

**Issue by WLLR9505** [facebook-atom/atom-ide-debugger-native-gdb#4]
Please, update the readme with:
- How to configure and start;
- Dependencies;
- [etc].

_I use a debugger (C/C++) in VS Code (with cygwin), I use Atom only to web languages, this extension do not have clear information on how to use, I really want to use Atom as my main editor, and that's the last extension I need for this.._

**Comment by ebluestein** [comment]
Sorry, Native debugging with atom-ide-debugger is not supported on Windows. This feature requires Mac or Linux.
