### ISSUE TITLE
can't launch debugger with '*' in args field

### ISSUE THREAD

**Issue by dpriedel** [facebook-atom/atom-ide-debugger-native-gdb#5]
Hi

Steps to produce:

1. click Launch debugger button.
2. In dialog window, put value into the args field.  --x=5.*

nothing happens.

Attached is console log 
[launch_debug_with_command_line_options.log](https://github.com/facebook-atom/atom-ide-debugger-native-gdb/files/1955316/launch_debug_with_command_line_options.log)

**Comment by Goom11** [comment]
@dpriedel , this issue has been fixed with https://github.com/facebook/nuclide/commit/83a2c7205be65e4102b00fe8897b9365a21ccaf1

:) Let us know if anything else is not working.
