### ISSUE TITLE
when attempting to attach a debugger, this one is not found

### ISSUE THREAD

**Issue by GabeRundlett** [facebook-atom/atom-ide-debugger-native-gdb#7]
After installing both "atom-ide-ui" and "atom-ide-debugger-native-gdb" from the command line, restarting atom and opening a project, still, no debuggers are found. If I install the NodeJS debugger listed on the same site as this one (atom-ide-ui repo page) it is listed in the debugger list and works perfectly.

![image](https://user-images.githubusercontent.com/28205981/43748677-e18723b8-99be-11e8-9297-8a81b12f727b.png)
![image](https://user-images.githubusercontent.com/28205981/43748735-22cb6c30-99bf-11e8-91c9-c19aa83e1fca.png)

I do have mingw (installed/in my environment variables) and have been using it to compile my code manually from the command line. I am unaware of anything else that is required for this to work, and have looked up this issue but sadly did not find much. I would be appreciative of any help.

I am sorry if this would be the wrong place to be posting this, but I didn't know where else to go.

system specs:  //may not matter but might as well include it
Windows 10 64 bit
AMD Ryzen 1500x cpu
8gb ddr4 memory
GeForce GTX 1070 8gb-vram (evga)

**Comment by ebluestein** [comment]
Sorry, native debugging via Nuclide / atom-ide is not currently supported on Windows.  The version of gdb  and LLDB we use requires Mac or Linux.

**Comment by yaoguilv** [comment]
hope to support on windows quickly
